on:
  push:
    branches: [master]
  pull_request:

name: build

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: install-rustup
          profile: minimal
          toolchain: stable
          override: true
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        name: Cargo build
        with:
          command: cargo check
