on:
  push:
    branches: [master]
  pull_request:

name: clippy

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: install-rustup
          profile: minimal
          toolchain: stable
          override: true
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        with:
          command: cargo clippy
          args: -- -D warnings
          annotations: true

