
on:
  push:
    branches: [master]
  pull_request:

name: codespell

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          ignore_words_list: "crate,ser,inout"
